sudo: false
language: rust
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    - rust: nightly
      env: FEATURES=logging
    - rust: nightly
      env: FEATURES=''
    - rust: stable
      env: FEATURES=logging
    - rust: stable
      env: FEATURES=''
os:
  - linux

script:
  - cargo test
